---
apiVersion: v1
kind: Service
metadata:
  name: presto
spec:
  ports:
  - port: 8080
  selector:
    app: presto-coordinator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-coordinator
spec:
  selector:
    matchLabels:
      app: presto-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
      - name: metastore
        image: thingsolver/fb-presto
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: solver-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: solver-bucket
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: presto-cfg-vol
          mountPath: opt/presto-server/etc/config.properties
          subPath: config.properties.coordinator
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/node.properties.template
          subPath: node.properties.template
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/catalog/hive.properties.template
          subPath: hive.properties.template
        command: ['/opt/autoconfig_and_launch.sh']
        resources:
          requests:
            memory: "8G"
            cpu: 2
        imagePullPolicy: Always
      volumes:
        - name: presto-cfg-vol
          configMap:
            name: presto-cfg
      imagePullSecrets:
      - name: regcred

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: presto-worker
spec:
  serviceName: presto-worker 
  replicas: 2
  selector:
    matchLabels:
      app: presto-worker
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - name: metastore
        image: thingsolver/fb-presto
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: solver-bucket
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: solver-bucket
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: presto-cfg-vol
          mountPath: opt/presto-server/etc/config.properties
          subPath: config.properties.worker
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/node.properties.template
          subPath: node.properties.template
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/catalog/hive.properties.template
          subPath: hive.properties.template
        - name: presto-tmp-data
          mountPath: /tmp
        command: ['/opt/autoconfig_and_launch.sh']
        resources:
          requests:
            memory: "8G"
            cpu: 2
        imagePullPolicy: Always
      volumes:
        - name: presto-cfg-vol
          configMap:
            name: presto-cfg
      imagePullSecrets:
      - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: presto-tmp-data
    spec:
      storageClassName: rook-cephfs
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: presto-cli
spec:
  containers:
  - name: presto-cli
    image: thingsolver/presto-cli
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
  restartPolicy: Always
  imagePullSecrets:
  - name: regcred
